# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    peadm: "puppetlabs/peadm"
  symlinks:
    "boltserver_spec": "#{source_dir}/spec/acceptance/boltserver_spec"
    "peadm_spec": "#{source_dir}/fixtures/modules/peadm/spec/acceptance/peadm_spec"
