---
os: linux
dist: xenial
language: ruby
cache: bundler
before_script:
  - wget https://apt.puppet.com/puppet-tools-release-xenial.deb
  - sudo dpkg -i puppet-tools-release-xenial.deb
  - sudo apt-get update
  - sudo apt-get install pdk -y
  - pdk --version
script:
  - 'pdk $CHECK'
stages:
  - static
  - spec
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="validate --puppet-version=7.4.1" # PE 2021.7
      stage: static
    -
      env: CHECK="test unit --puppet-version=6.21.1" # PE 2019.8
      stage: spec
    -
      env: CHECK="test unit --puppet-version=7.4.1" # PE 2021.7
      stage: spec
branches:
  only:
    - main
notifications:
  email: false